; standard LANGID, charset pair for US English, unicode
; default is 0,1200 for language neutral, unicode
companyname = s-ball
LegalCopyright= Copyright s-ball 2025-current, MIT license
; missing required keys will receive reasonable values based on the
;  application name
